# Generated by Django 4.2.4 on 2023-10-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompts',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prompts',
            name='sensitivity_to_cold',
            field=models.CharField(max_length=100),
        ),
    ]
