# Generated by Django 4.2.4 on 2023-08-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.CharField(max_length=50)),
                ('wind', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('feels_like', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
            ],
        ),
    ]
