# Generated by Django 4.2.4 on 2023-08-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0002_rename_questions_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('temperature_high', models.CharField(max_length=50)),
                ('temperature_low', models.CharField(max_length=50)),
                ('temperature_avg', models.CharField(max_length=50)),
                ('wind_mph', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('feels_like', models.CharField(max_length=50)),
                ('humidity', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.IntegerField(blank=True, default=0)),
                ('survey_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
