# Generated by Django 4.2.4 on 2023-08-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weather',
            name='zip_code',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
