# Generated by Django 4.2.4 on 2023-08-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zip',
            new_name='zip_code',
        ),
    ]
