# Generated by Django 4.2.4 on 2023-08-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_zip_user_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='laslt_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
    ]
