# Generated by Django 4.2.4 on 2023-10-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_rename_neck_clothing_jacket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothing',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ['id']},
        ),
    ]
