# Generated by Django 4.2.4 on 2023-08-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_question_survey_id_alter_survey_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='weather_id',
        ),
    ]
