# Generated by Django 4.2.4 on 2023-08-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
        ('survey', '0003_remove_survey_weather_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='weather_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='survey_weather', to='weather.weather'),
            preserve_default=False,
        ),
    ]
