# Generated by Django 4.2.4 on 2023-08-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_weather_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='weather_id',
            new_name='weather',
        ),
    ]
